version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data/

  api:
    build: api
    ports:
      - "8888:8888"
    command: "python main.py"
    environment:
      - DB_URI=$DB_URI
      
volumes:
  db-data:
